name: Create Action draft-release
"on":
    pull_request:
        paths:
            - actions/*
            - actions/draft-release/*
    push:
        branches:
            - main
        paths:
            - actions/*
            - actions/draft-release/*
    release:
        types:
            - published
jobs:
    create-action:
        name: Create Action
        runs-on:
            - ubuntu-latest
        steps:
            - name: Docker login ghcr.io
              if: ${{ (github.event_name != 'pull_request' || ! github.event.pull_request.head.repo.fork) && (github.actor != 'dependabot[bot]') }}
              uses: docker/login-action@v2
              with:
                password: ${{ secrets.JAVA_GITHUB_TOKEN }}
                registry: ghcr.io
                username: ${{ secrets.JAVA_GITHUB_USERNAME }}
            - uses: actions/checkout@v3
            - name: Create Action
              run: |
                #!/usr/bin/env bash

                set -euo pipefail

                echo "::group::Building ${TARGET}:${VERSION}"
                  docker build \
                    --file actions/Dockerfile \
                    --build-arg "SOURCE=${SOURCE}" \
                    --tag "${TARGET}:${VERSION}" \
                    .
                echo "::endgroup::"

                if [[ "${PUSH}" == "true" ]]; then
                  echo "::group::Pushing ${TARGET}:${VERSION}"
                    docker push "${TARGET}:${VERSION}"
                  echo "::endgroup::"
                else
                  echo "Skipping push"
                fi
              env:
                PUSH: ${{ github.event_name != 'pull_request' }}
                SOURCE: draft-release
                TARGET: ghcr.io/paketo-buildpacks/actions/draft-release
                VERSION: main
